import "~/styles/globals.css";

import { type Metadata } from "next";
import { Plus_Jakarta_Sans  } from "next/font/google";

import { AppSidebar } from "~/components/shared/AppSidebar";
import { SidebarProvider } from "~/components/ui/sidebar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${plusJakarta.variable}`}>
      <body>
        <TRPCReactProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 py-2">{children}</main>
          </SidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
